name: Deploy Frontend Resume to Azure Blob

on:
  push:
    branches: [master]  # or main if that's your default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Blob Storage
      uses: azure/cli@v1
      with:
        inlineScript: |
          echo "Uploading all files to Azure Blob Storage..."
          
          # Upload all files (excluding git and github folders)
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source . \
            --auth-mode key \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --overwrite true
          
          echo "✅ All files uploaded successfully!"

    - name: Purge Azure CDN
      uses: azure/cli@v1
      with:
        inlineScript: |
          if [ -n "${{ secrets.AZURE_CDN_ENDPOINT }}" ] && [ -n "${{ secrets.AZURE_CDN_PROFILE_NAME }}" ] && [ -n "${{ secrets.AZURE_RESOURCE_GROUP }}" ] && [ -n "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]; then
            echo "Purging CDN cache..."
          az afd endpoint purge \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} \
            --endpoint-name ${{ secrets.AZURE_CDN_ENDPOINT }} \
            --content-paths '/*'
            echo "✅ CDN cache purged successfully!"
          else
            echo "ℹ️  CDN configuration incomplete, skipping CDN purge"
          fi

    - name: Display deployment info
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "📝 Files uploaded to storage account: ${{ secrets.AZURE_STORAGE_ACCOUNT }}"
        echo "🌐 Your resume should now be available at your static website URL"